### ISSUE TITLE
Toolkit js has error

### ISSUE THREAD

**Issue by gemmaleigh** [alphagov/govuk_frontend_alpha#143]
I'm seeing this error in the npm_test app:

```
toolkit.min.js?0.0.1:1 Uncaught TypeError: e is not a function
    at toolkit.min.js?0.0.1:1
    at toolkit.min.js?0.0.1:1
(anonymous) @ toolkit.min.js?0.0.1:1
(anonymous) @ toolkit.min.js?0.0.1:1
```

**Comment by gemmaleigh** [comment]
This is because the toolkit JavaScript files use jQuery and it isn't provided by the template.

We're not seeing this error in Fractal as Google hosted jQuery is [loaded in the _preview template](https://github.com/alphagov/govuk_frontend_alpha/blob/master/src/components/_preview/_preview.njk#L29).

Ideally, the _preview template in Fractal should extend the govuk_layout template.

**Comment by dsingleton** [comment]
I've added an issue to remind us to reconsider this for beta: https://github.com/alphagov/govuk_frontend_alpha/issues/202

**Comment by gemmaleigh** [comment]
I'm going to close this as we've got a reminder issue in its place.
