### ISSUE TITLE
Fractal navigation alignment

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_frontend_alpha#211]
Before:

![image](https://cloud.githubusercontent.com/assets/2445413/22835642/56cb94c4-efb1-11e6-9408-9cb406ebe93e.png)

After:

![screen shot 2017-02-10 at 16 50 00](https://cloud.githubusercontent.com/assets/2445413/22835534/06e37b2a-efb1-11e6-97ca-172b2686965c.png)

I could do a PR if you wanted?

**Comment by gemmaleigh** [comment]
@nickcolley That looks much better! Feel free, PRs are always welcome 👍

**Comment by dsingleton** [comment]
Please don't do a PR. I'm working on Fractal UI / Tech doc styling at the moment.
