### ISSUE TITLE
Fix scss lint warnings

### ISSUE THREAD

**Issue by gemmaleigh** [alphagov/govuk_frontend_alpha#24]
The .sass-lint.yml file being used is generated from [gds-sass-styleguide.yml](https://raw.githubusercontent.com/alphagov/govuk-lint/master/configs/scss_lint/gds-sass-styleguide.yml) which is part of GOV.UK lint.

We should also fix the scss files so that they no longer result in warnings when 'gulp styles' is run to compile the scss.

**Comment by robinwhittleton** [comment]
The inline warnings are supported by govuk-lint’s scss-lint, but not by sass-lint. This is currently being implemented in https://github.com/sasstools/sass-lint/pull/677

**Comment by gemmaleigh** [comment]
This was fixed in #47.
