### ISSUE TITLE
Break elements and modifiers outside of blocks rather than nesting using &

### ISSUE THREAD

**Issue by stevenadams** [alphagov/govuk_frontend_alpha#34]
Break elements and modifiers outside of blocks rather than nesting using &. An example of this would be in components/_breadcrumb.scss. 

.gv-c-breadcrumb {}

.gv-c-breadcrumb__list {}

This makes the code base more searchable and straightforward, making it easier to maintain. The current format also encourages the (bad) habit of excessive nesting.

**Comment by gemmaleigh** [comment]
Thanks @stevenadams, we've included this in our documentation over here: 
https://github.com/alphagov/govuk-frontend/blob/master/docs/coding-standards/css.md#nesting

I'm closing this issue now we have it covered.
